language: python
python:
  - "3.9"

services:
  - docker

before_install: 
  - echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

before_script: pip install docker-composer

script: 
  - docker-compose run app sh -c "python manage.py test"